GoFundX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'projects.views.custom_404'
handler500 = 'projects.views.custom_500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('go_fund_auth.urls')),
    path('projects/', include('projects.urls')),
    path('accounts/', include('allauth.urls')),
    # path('oauth/', include('social_django.urls', namespace='social')),
]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('create/', views.create_project, name='create_project'),
    path('', views.project_list, name='projects'),
    path('<int:id>', views.project_details, name='project_details'),
    path('update/<int:id>', views.update_project, name='update_project'),
    path('delete/<int:id>', views.delete_project, name='delete_project'),
    path('report/<int:id>/', views.report_project, name='report_project'),
    path('donate/<int:id>', views.donate, name='donate'),
    path('search/', views.search_results, name='search_results'),
    path('categories/<int:category_id>', views.category_projects, name='category_projects'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('report_comment/<int:comment_id>/', views.report_comment, name='report_comment'),
    path('trigger-error/', views.trigger_server_error, name='trigger_server_error'),
]

projects/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from PIL import Image
from datetime import datetime

from .models import Category, Tag, Project, Picture, Comment, Donation, Rating


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'
        exclude = ['created_at', 'updated_at']


class PictureFormSet(forms.BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for i in range(0, self.total_form_count()):
            form = self.forms[i]
            # is_main will be True for the first form, False for the rest.
            is_main = i == 0
            form.fields['is_main'].initial = is_main

    def clean(self):
        super().clean()

        # Check that at least one image has been uploaded
        if any(self.errors):
            return
        if not any(cleaned_data.get('image') for cleaned_data in self.cleaned_data):
            raise forms.ValidationError('At least one image must be uploaded.')


class PictureForm(forms.ModelForm):
    # Add style to the picture fields
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    is_main = forms.BooleanField(
        initial=False, required=False, widget=forms.HiddenInput())

    class Meta:
        model = Picture
        fields = '__all__'
        exclude = ['created_at', 'updated_at', 'project']

    def clean_image(self):
        image = self.cleaned_data.get('image')
        if image:
            img = Image.open(image)
            width, height = img.size

            # Set the minimum width based on whether the image is the main picture
            min_width = 1920 if self.cleaned_data.get('is_main') else 500

            if width < min_width:
                raise ValidationError(
                    f'The image is too small, it should be at least {min_width}px wide.')

            return image


class ProjectForm(forms.ModelForm):
    # Add style to the project creation form
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if visible.name != 'existing_tags':
                visible.field.widget.attrs['class'] = 'form-control'

        self.fields['title'].widget.attrs['placeholder'] = 'Project Title'
        self.fields['details'].widget.attrs['placeholder'] = 'Write the details of the project'
        self.fields['total_target'].widget.attrs['placeholder'] = 'e.g. 5000'
        self.fields['custom_tags'].widget.attrs['placeholder'] = 'e.g. Help Palestinians, Help children'

    start_time = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))
    end_time = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    existing_tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    custom_tags = forms.CharField(max_length=255, required=False)

    class Meta:
        model = Project
        fields = '__all__'
        exclude = ['created_at', 'updated_at', 'tags',
                   'total_raised', 'avg_rating', 'reports_num', 'is_featured', 'user', 'reported_by']

    def clean(self):
        cleaned_data = super().clean()

        is_main = cleaned_data.get('is_main')
        pictures = cleaned_data.get('pictures')

        # If the main picture is required, make sure that there is at least one picture submitted
        if is_main and not pictures:
            raise ValidationError('The main picture is required.')

        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)

        # ... handle tags ...
        if commit:
            instance.user = self.user
            instance.save()

        return instance


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

        self.fields['content'].widget.attrs['placeholder'] = 'Your comment here'
        self.fields['content'].widget.attrs['rows'] = '4'

    class Meta:
        model = Comment
        fields = '__all__'
        exclude = ['created_at', 'updated_at', 'user', 'project', 'reports_num', 'reported', 'reported_by', 'parent']
        labels = {
            "content": ""
        }


class DonationForm(forms.ModelForm):
    class Meta:
        model = Donation
        fields = '__all__'
        exclude = ['created_at', 'updated_at']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        exclude = ['created_at', 'updated_at']


class RatingForm(forms.Form):
    rating = forms.IntegerField(
        widget=forms.NumberInput(attrs={'type': 'range', 'min': 1, 'max': 5, 'step': 1})
    )

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.forms import modelformset_factory
from django.db.models import Avg
from django.contrib import messages
from django.urls import reverse
from decimal import Decimal
from go_fund_auth.models import CustomUser
from .models import Category, Tag, Project, Picture, Comment, Donation, Rating
from .forms import ProjectForm, PictureForm, CommentForm, \
    PictureFormSet as PictureFormset, RatingForm


# Create your views here.
def create_project(request):
    PictureFormSet = modelformset_factory(Picture, form=PictureForm, extra=5, formset=PictureFormset)

    if request.method == 'POST':
        form = ProjectForm(request.POST)
        initial = [{'is_main': True if i == 0 else False} for i in range(5)]
        formset = PictureFormSet(request.POST, request.FILES, queryset=Picture.objects.none(), initial=initial)

        if form.is_valid() and formset.is_valid():
            form.user = request.user
            form.save()
            instances = formset.save(commit=False)  # Save each Picture instance without committing to the database
            if instances:  # Check if there are any pictures
                instances[0].is_main = True  # Set is_main for the first picture

            project = form.save()  # Save the project instance to the database

            existing_tags = form.cleaned_data['existing_tags']
            project.tags.set(existing_tags)  # Now you can set the tags

            custom_tags = form.cleaned_data['custom_tags']
            if custom_tags:
                custom_tags_list = [tag.strip() for tag in custom_tags.split(',')]
                for tag_name in custom_tags_list:
                    tag, _ = Tag.objects.get_or_create(name=tag_name)
                    project.tags.add(tag)

            for instance in instances:
                instance.project = project  # Assign the project to the picture
                instance.save()  # Now save the picture instance to the database

            return redirect('projects')
    else:
        form = ProjectForm()
        formset = PictureFormSet(queryset=Picture.objects.none())
    return render(request, 'projects/create_project.html', {'form': form, 'formset': formset})


def project_list(request):
    projects = Project.objects.all()

    for project in projects:
        if project.total_target != 0:  # Avoid division by zero
            project.progress = (project.total_raised / project.total_target) * 100
        else:
            project.progress = 0

        # Calculate the average rating
        project.average_rating = Rating.objects.filter(project=project).aggregate(Avg('rating'))['rating__avg'] or 0
        print(project.average_rating)
        # Calculate the half-star threshold
        project.half_star_threshold = round(project.average_rating * 2) / 2

    return render(request, 'projects/projects.html', {'projects': projects, 'rating_range': range(1, 6)})


def project_details(request, id):
    # project = get_object_or_404(Project, pk=id)
    project = Project.objects.annotate(avg_rating=Avg('rating__rating')).get(id=id)
    comment_form = CommentForm()
    rating_form = RatingForm()

    if project.total_target != 0:  # Avoid division by zero
        project.progress = (project.total_raised / project.total_target) * 100
    else:
        project.progress = 0

    # Calculate the average rating
    project.average_rating = Rating.objects.filter(project=project).aggregate(Avg('rating'))['rating__avg'] or 0
    print(project.average_rating)
    # Calculate the half-star threshold
    project.half_star_threshold = round(project.average_rating * 2) / 2

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        # Handle comment submission
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.user = request.user
            new_comment.project = project

            # Check if the comment is a reply to another comment
            parent_id = request.POST.get('parent_id')
            if parent_id:
                # If it is, set the parent of the comment
                new_comment.parent_id = int(parent_id)

            new_comment.save()
            comment_form = CommentForm()
            return redirect('project_details', id=id)

        rating_form = RatingForm(request.POST)
        if rating_form.is_valid():
            user_rating = rating_form.cleaned_data['rating']
            rating, created = Rating.objects.get_or_create(user=request.user, project=project)
            rating.rating = user_rating
            rating.save()
            return redirect('project_details', id=id)

    if request.user.is_authenticated:
        try:
            rating = Rating.objects.filter(user=request.user, project=project).first()
            if rating:
                user_rating = rating.rating
            else:
                user_rating = None
        except Rating.DoesNotExist:
            user_rating = None
    else:
        rating = None
        user_rating = None

    related_projects = Project.objects.filter(category=project.category).exclude(id=project.id)[:3]
    latest_ratings = Rating.objects.filter(project=project).order_by('-id')[:5]

    # comments = project.comment_set.all()
    comments = project.comment_set.filter(parent__isnull=True)

    for related_project in related_projects:
        if related_project.total_target != 0:  # Avoid division by zero
            related_project.progress = (related_project.total_raised / related_project.total_target) * 100
        else:
            related_project.progress = 0

        # Calculate the average rating
        related_project.average_rating = Rating.objects.filter(project=project).aggregate(Avg('rating'))['rating__avg'] or 0

        # Calculate the half-star threshold
        related_project.half_star_threshold = int(related_project.average_rating) + 0.5

    return render(request, 'projects/project_details.html',
                  {'project': project, 'comment_form': comment_form,
                   'comments': comments, 'rating': rating,
                   'rating_range': range(1, 6),
                   'rating_form': rating_form,
                   'user_rating': user_rating,
                   'related_projects': related_projects,
                   'latest_ratings': latest_ratings
                   })


def update_project(request, id):
    project = get_object_or_404(Project, pk=id)
    PictureFormSet = modelformset_factory(Picture, form=PictureForm, extra=5, formset=PictureFormset)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        formset = PictureFormSet(request.POST, request.FILES, queryset=Picture.objects.filter(project=project))
        if form.is_valid() and formset.is_valid():
            project = form.save(commit=False)  # Don't save the Project instance yet
            project.user = request.user  # Assign the user to the project
            project.save()  # Now save the Project instance to the database
            instances = formset.save(commit=False)
            for instance in instances:
                instance.project = project
                instance.save()
            return redirect('project_details', id=id)
    else:
        form = ProjectForm(instance=project)
        formset = PictureFormSet(queryset=Picture.objects.filter(project=project))
    return render(request, 'projects/update_project.html', {'form': form, 'formset': formset})


def delete_project(request, id):
    project = get_object_or_404(Project, pk=id)
    if project.total_raised >= (project.total_target * Decimal('0.25')):
        return render(request, 'projects/delete_project.html', context={'project': project,'error': 'Cannot delete project as it has already raised 25% of its target.'})

    if request.method == 'POST':
        # Clear all messages
        storage = messages.get_messages(request)
        storage.used = True

        # Check if total_raised is equal to or more than 25% of total_target
        if project.total_raised >= (project.total_target * Decimal('0.25')):
            return redirect(reverse('project_details', args=[id]), context={'error': 'Cannot delete project as it has already raised 25% of its target.'})
        else:
            project.delete()
            return redirect(reverse('projects'))

    return render(request, 'projects/delete_project.html', {'project': project})


def donate(request, id):
    if request.method == 'POST':
        project = Project.objects.get(id=id)
        try:
            user = CustomUser.objects.get(id=request.user.id)
        except CustomUser.DoesNotExist:
            user = None

        amount = request.POST['flexDefault']
        if amount == "":
            amount = request.POST['flexRadioDefault']

        # Convert the amount to decimal
        amount = Decimal(amount)

        # Calculate the remaining amount of the total target
        remaining_amount = project.total_target - project.total_raised

        # Check if the donation amount is valid
        if amount <= 0 or amount > remaining_amount:
            # If not, return an error message
            return render(request, 'projects/donate.html', {'error': 'Invalid donation amount.'})

        donation = Donation(amount=amount, user=user, project=project)
        donation.save()

        # Add the donation amount to the total raised
        project.total_raised += amount
        project.save()

        return redirect('project_details', id=project.id)
    return render(request, 'projects/donate.html')


def search_results(request):
    query = request.GET.get('search')
    search_type = request.GET.get('searchType')

    if search_type == 'names':
        results = Project.objects.filter(title__icontains=query)
    else:
        results = Project.objects.filter(tags__name__icontains=query)

projects/templates/projects/category_projects.html
{% extends 'base.html' %}

{% block content %}
    <div class="container py-5">
        <h2 class="mb-5" style="color: var(--secondary-color)">Projects in Category: <span style="color: var(--primary-color)">{{ category.name }}</span></h2>
        <div class="row">
            {% include 'projects/projects_list.html' with projects=projects %}
        </div>
    </div>
{% endblock %}

projects/templates/projects/create_project.html
{% extends 'base.html' %}
{% load static %}

{% block home %}
class="nav-link click-scroll"
{% endblock %}


{% block content %}
    <!--adding style to the checkbox-->
    <style>
        #id_existing_tags > div {
            display: inline;
            margin-right: 5px;
        }
    </style>

    <section class="volunteer-section section-padding" id="section_4">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-12">
                    <h1 class="text-white mb-4 text-center">Create New Project</h1>
                    <form
                            method="post"
                            enctype="multipart/form-data"
                            class="custom-form volunteer-form mb-5 mb-lg-0">

                        {% csrf_token %}
                        {{ form.as_p }}
                        {{ formset.management_form }}
                        {% if formset.non_form_errors %}
                            <div class="alert alert-danger">
                                {{ formset.non_form_errors }}
                            </div>
                        {% endif %}
                        {% for picture_form in formset %}
                            {{ picture_form.as_p }}
                        {% endfor %}
                        <button type="submit" class="form-control">Add New Project</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

projects/templates/projects/delete_project.html
{% extends "base.html" %}

{% block home %}
class="nav-link click-scroll"
{% endblock %}

{% block content %}
<section class="section-padding">
    <div class="container">
        {% if error %}
        <h3 class="mb-5 text-danger">{{error}}</h3>
        <a href="{% url 'project_details' project.id%}" class="btn custom-btn">Go back</a>
        {% else %}
        <h2 class="mb-5">Are you sure you want to delete your Project {{project.title}}?</h2>
        <form method="post" class="custom-form mb-3">
        {% csrf_token %}
            <button type="submit" class="btn btn-primary p-3 bg-danger">Yes, delete my project</button>
        </form>
        <a href="{% url 'project_details' project.id%}" class="m-3">No, take me back</a>
        {% endif %}
    </div>
</section>
{% endblock %}

projects/templates/projects/donate.html
{% extends 'base.html' %}
{% load static %}

{% block home %}
    class="nav-link click-scroll"
{% endblock %}

{% block content %}
    <section class="donate-section">
        <div class="section-overlay"></div>
        <div class="container">
            <div class="row">
                {% if error %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                {% endif %}


                <div class="col-lg-6 col-12 mx-auto">
                    <form class="custom-form donate-form" method="post">
                        {% csrf_token %}

                        <h3 class="mb-4">Make a donation</h3>

                        <div class="row">
                            <div class="col-lg-12 col-12">
                                <h5 class="mt-2 mb-3">Select an amount</h5>
                            </div>

                            <div class="col-lg-3 col-md-6 col-6 form-check-group">
                                <div class="form-check form-check-radio">
                                    <input class="form-check-input" type="radio" value="10" name="flexRadioDefault"
                                           id="flexRadioDefault1">
                                    <label class="form-check-label" for="flexRadioDefault1">
                                        $10
                                    </label>
                                </div>
                            </div>

                            <div class="col-lg-3 col-md-6 col-6 form-check-group">
                                <div class="form-check form-check-radio">
                                    <input class="form-check-input" type="radio" value="15" name="flexRadioDefault"
                                           id="flexRadioDefault2">
                                    <label class="form-check-label" for="flexRadioDefault2">
                                        $15
                                    </label>
                                </div>
                            </div>

                            <div class="col-lg-3 col-md-6 col-6 form-check-group">
                                <div class="form-check form-check-radio">
                                    <input class="form-check-input" type="radio" value="20" name="flexRadioDefault"
                                           id="flexRadioDefault3">
                                    <label class="form-check-label" for="flexRadioDefault3">
                                        $20
                                    </label>
                                </div>
                            </div>

                            <div class="col-lg-3 col-md-6 col-6 form-check-group">
                                <div class="form-check form-check-radio">
                                    <input class="form-check-input" type="radio" value="30" name="flexRadioDefault"
                                           id="flexRadioDefault4">
                                    <label class="form-check-label" for="flexRadioDefault4">
                                        $30
                                    </label>
                                </div>
                            </div>

                            <div class="col-lg-3 col-md-6 col-6 form-check-group">
                                <div class="form-check form-check-radio">
                                    <input class="form-check-input" type="radio" value="40" name="flexRadioDefault"
                                           id="flexRadioDefault5">
                                    <label class="form-check-label" for="flexRadioDefault5">
                                        $40
                                    </label>
                                </div>
                            </div>

                            <div class="col-lg-3 col-md-6 col-6 form-check-group">
                                <div class="form-check form-check-radio">
                                    <input class="form-check-input" type="radio" value="50" name="flexRadioDefault"
                                           id="flexRadioDefault6">
                                    <label class="form-check-label" for="flexRadioDefault6">
                                        $50
                                    </label>
                                </div>
                            </div>

                            <div class="col-lg-6 col-12 form-check-group">
                                <div class="input-group">
                                    <span class="input-group-text" id="basic-addon1">$</span>

                                    <input type="number" class="form-control" name="flexDefault"
                                           placeholder="Custom amount" aria-describedby="basic-addon1">
                                </div>
                            </div>

                            <div class="col-lg-12 col-12">
                                <h5 class="mt-4 pt-1">Choose Payment</h5>
                            </div>

                            <div class="col-lg-12 col-12 mt-2">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="DonationPayment"
                                           id="flexRadioDefault9">
                                    <label class="form-check-label" for="flexRadioDefault9">
                                        <i class="bi-credit-card custom-icon ms-1"></i>
                                        Debit or Credit card
                                    </label>
                                </div>

                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="DonationPayment"
                                           id="flexRadioDefault10">
                                    <label class="form-check-label" for="flexRadioDefault10">
                                        <i class="bi-paypal custom-icon ms-1"></i>
                                        Paypal
                                    </label>
                                </div>

                                <button type="submit" class="form-control mt-4">Submit Donation</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

projects/templates/projects/projects.html
{% extends 'base.html' %}
{% load static %}

{% block home %}
    class="nav-link click-scroll"
{% endblock %}

{% block products %}
    class="nav-link click-scroll active"
{% endblock %}

{% block content %}

    <section class="py-5">
        <div class="container">
            <h2 class="mb-5">Projects</h2>
            <div class="row">
                {% include 'projects/projects_list.html' with projects=projects %}
            </div>
            {% if user.is_authenticated %}
            <div class="d-flex justify-content-center mt-4">
                <a href="{% url 'create_project' %}" class="btn custom-btn mt-4">Add Project</a>
            </div>
            {% endif %}
        </div>
    </section>

{% endblock %}

projects/templates/projects/projects_list.html
{% for project in projects %}
    <div class="col-lg-4 col-md-6 col-12 mb-4 d-flex">
        <div class="custom-block-wrap">
            {% with project.pictures.all|first as first_picture %}
                <a href="{% url 'project_details' project.id %}">
                    <img src="{{ first_picture.image.url }}" class="custom-block-image img-fluid" style="height:255px !important" alt="">
                </a>
            {% endwith %}

            <div class="custom-block">
                <a href="{% url 'project_details' project.id %}">
                    <div class="custom-block-body">
                        <div class="d-flex" style="position: relative;">
                            <div style="position: absolute; margin-top: -25px; right: 0;">
                                {% for i in rating_range %}
                                    {% if i <= project.average_rating %}
                                        <i class="fas fa-star" style="color: var(--secondary-color);"></i>
                                    {% elif i <= project.half_star_threshold %}
                                        <i class="fas fa-star-half-alt"
                                           style="color: var(--secondary-color);"></i>
                                    {% else %}
                                        <i class="far fa-star" style="color: var(--secondary-color);"></i>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <h5 class="mb-3" style="font-size: 1.3em;">{{ project.title|upper }}</h5>
                        </div>
                        <p>{{ project.details|upper|truncatechars:45 }}</p>

                        <div>
                            {% for tag in project.tags.all %}
                                <span class="badge rounded-pill py-2 px-3">{{ tag.name }}</span>
                            {% endfor %}
                        </div>

                        <!-- Display the average rating as stars -->

                        <div class="progress mt-4">
                            <div class="progress-bar" role="progressbar"
                                 style="width: {{ project.progress }}%;"

                                 aria-valuenow="{{ project.progress }}"
                                 aria-valuemin="0" aria-valuemax="100"></div>
                        </div>

                        <div class="d-flex my-2">
                            <p class="mb-0">
                                <strong>Raised:</strong>
                                ${{ project.total_raised }}
                            </p>

                            <p class="ms-auto mb-0">
                                <strong>Goal:</strong>
                                ${{ project.total_target }}
                            </p>
                        </div>
                    </div>
                </a>
                <div class="spacer" style="margin-bottom: 30px;"></div>
                <a href="{% url 'donate' project.id %}" class="custom-btn btn" style="position: absolute; bottom: 0; width: 100%;">Donate now</a>
            </div>
        </div>
    </div>
{% empty %}
    <p>No projects found.</p>
{% endfor %}

projects/templates/projects/update_project.html
{% extends 'base.html' %}
{% load static %}

{% block home %}
    class="nav-link click-scroll"
{% endblock %}

{% block content %}
    <!--adding style to the checkbox-->
    <style>
        #id_existing_tags > div {
            display: inline;
            margin-right: 5px;
        }
    </style>

    <section class="volunteer-section section-padding" id="section_4">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-12">
                    <h1 class="text-white mb-4 text-center">Update Project</h1>
                    <form method="post" enctype="multipart/form-data" class="custom-form volunteer-form mb-5 mb-lg-0">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {{ formset.management_form }}
                        {% if formset.non_form_errors %}
                            <div class="alert alert-danger">
                                {{ formset.non_form_errors }}
                            </div>
                        {% endif %}
                        {% for picture_form in formset %}
                            {{ picture_form.as_p }}
                        {% endfor %}
                        <button type="submit" class="form-control">Update Project</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}